
name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'why this workflow is triggered'     
        required: true
        default: 'manually deploy site'

jobs:
  deploy_gh_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Install mdbook
        run: cargo install mdbook mdbook-toc
      - name: Build docs
        working-directory: ./docs
        run: mdbook build
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs/book
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
